apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"nodejs-build:latest","namespace":"eap-demo-sergio"},"fieldPath":"spec.template.spec.containers[?(@.name==\"nodejs-build\")].image"}]'
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: "2021-12-14T10:21:54Z"
  generation: 5
  labels:
    app: my-nodejs-app
    app.kubernetes.io/component: my-nodejs-app
    app.kubernetes.io/instance: my-nodejs-app
  name: my-nodejs-app
  namespace: eap-demo-sergio
  resourceVersion: "1058626"
  selfLink: /apis/apps/v1/namespaces/eap-demo-sergio/deployments/my-nodejs-app
  uid: daef96d0-302f-4cb3-9b41-ac667383f8a7
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      deployment: my-nodejs-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        deployment: my-nodejs-app
    spec:
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/eap-demo-sergio/nodejs-build@sha256:44575258bdfe030b4a0174339681be0bbf58fbea3034a5840662246c71bacd50
        imagePullPolicy: IfNotPresent
        name: nodejs-build
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 3
  conditions:
  - lastTransitionTime: "2021-12-14T10:21:54Z"
    lastUpdateTime: "2021-12-14T10:21:59Z"
    message: ReplicaSet "my-nodejs-app-865c447bbc" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2021-12-14T11:02:34Z"
    lastUpdateTime: "2021-12-14T11:02:34Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 5
  readyReplicas: 3
  replicas: 3
  updatedReplicas: 3
