{
 "title": "rhdg-meter - Benchmarks",
 "description": "Dashboard for rhdg-meter benchmarks",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "targethost", "label": "Target RHDG", "query": { "query": "label_values(targethost)" } },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{application=\"$application\"}, instance)"
    }
   },
   { "name": "interval", "label": "Interval", "query": "1m,5m,10m,20m,30m,1h,6h,12h,1d" },
   { "name": "benchmarkId", "label": "Benchmark ID", "query": { "query": "label_values(benchmarkId)" } },
   { "name": "application", "label": "Application", "query": { "query": "label_values(application)" } }
  ]
 },
 "panels": [
  { "title": "Quick Facts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{application=\"$application\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{application=\"$application\", instance=\"$instance\"}*1000"
    }
   ]
  },
  {
   "title": "Heap used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"heap\"})*100/sum(jvm_memory_max_bytes{application=\"$application\",instance=\"$instance\", area=\"heap\"})"
    }
   ]
  },
  {
   "title": "Non-Heap used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"nonheap\"})*100/sum(jvm_memory_max_bytes{application=\"$application\",instance=\"$instance\", area=\"nonheap\"})"
    }
   ]
  },
  { "title": "Benchmark: $benchmarkId", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Throughput",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(benchmark_seconds_count{application=\"$application\", instance=\"$instance\", benchmarkId=\"$benchmarkId\"}[$interval]) / rate(benchmark_seconds_sum{application=\"$application\", instance=\"$instance\", benchmarkId=\"$benchmarkId\"}[$interval])",
     "legendFormat": "ops/s"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(benchmark_seconds_max{application=\"$application\", instance=\"$instance\", benchmarkId=\"$benchmarkId\"})*1000",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "rate(benchmark_seconds_count{application=\"$application\", instance=\"$instance\", benchmarkId=\"$benchmarkId\"}[$interval]) / rate(benchmark_seconds_sum{application=\"$application\", instance=\"$instance\", benchmarkId=\"$benchmarkId\"}[$interval])",
     "legendFormat": "ops/s"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "rate(benchmark_seconds_sum{application=\"$application\", instance=\"$instance\", benchmarkId=\"$benchmarkId\"}[$interval]) / rate(benchmark_seconds_count{application=\"$application\", instance=\"$instance\", benchmarkId=\"$benchmarkId\"}[$interval])"
    }
   ]
  }
 ]
}